import fs from "node:fs";
import path from "node:path";

const repoRoot = path.resolve(new URL("..", import.meta.url).pathname);
const sourcePath = path.join(repoRoot, "webui/shared/console-pages.json");
const outputPath = path.join(repoRoot, "xc/ws63_team_network/src/ws63_console_pages.h");

const config = JSON.parse(fs.readFileSync(sourcePath, "utf8"));

function cString(value) {
  return String(value)
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n");
}

function defineString(name, value) {
  return `#define ${name} "${cString(value)}"`;
}

function tabDefines() {
  const tabs = Object.fromEntries(config.tabs.map((tab) => [tab.id, tab]));
  return [
    defineString("WS63_CONSOLE_TAB_STATUS_LABEL", tabs.status.label),
    defineString("WS63_CONSOLE_TAB_STATUS_HREF", tabs.status.href),
    defineString("WS63_CONSOLE_TAB_NODES_LABEL", tabs.nodes.label),
    defineString("WS63_CONSOLE_TAB_NODES_HREF", tabs.nodes.href),
    defineString("WS63_CONSOLE_TAB_EVENTS_LABEL", tabs.events.label),
    defineString("WS63_CONSOLE_TAB_EVENTS_HREF", tabs.events.href),
    defineString("WS63_CONSOLE_TAB_JSON_LABEL", tabs.json.label),
    defineString("WS63_CONSOLE_TAB_JSON_HREF", tabs.json.href),
  ];
}

function fieldDefines(prefix, fields) {
  return fields.map((field) => defineString(`${prefix}_${field.id.toUpperCase()}_LABEL`, field.label));
}

const lines = [
  "/* Auto-generated by tools/gen_ws63_console_header.mjs. Do not edit manually. */",
  "#ifndef WS63_CONSOLE_PAGES_H",
  "#define WS63_CONSOLE_PAGES_H",
  "",
  defineString("WS63_CONSOLE_BRAND", config.brand),
  defineString("WS63_CONSOLE_PRODUCT", config.product),
  defineString("WS63_CONSOLE_BOARD_TITLE", config.boardTitle),
  defineString("WS63_CONSOLE_BOARD_SUBTITLE", config.boardSubtitle),
  defineString("WS63_CONSOLE_HOSTED_URL", config.hostedConsoleUrl),
  defineString("WS63_CONSOLE_DEFAULT_DEVICE_API", config.defaultDeviceApiUrl),
  defineString("WS63_CONSOLE_BOARD_VERSION", config.boardVersion),
  "",
  ...tabDefines(),
  "",
  ...fieldDefines("WS63_CONSOLE_STATUS", config.statusFields),
  "",
  ...fieldDefines("WS63_CONSOLE_NODE", config.nodeFields),
  "",
  defineString("WS63_CONSOLE_EMPTY_NODES", config.empty.nodes),
  defineString("WS63_CONSOLE_EMPTY_EVENTS", config.empty.events),
  "",
  defineString("WS63_CONSOLE_COLOR_PAGE_BG", config.palette.pageBg),
  defineString("WS63_CONSOLE_COLOR_TEXT", config.palette.text),
  defineString("WS63_CONSOLE_COLOR_HEADER_BG", config.palette.headerBg),
  defineString("WS63_CONSOLE_COLOR_CARD_BG", config.palette.cardBg),
  defineString("WS63_CONSOLE_COLOR_BORDER", config.palette.border),
  defineString("WS63_CONSOLE_COLOR_MUTED", config.palette.muted),
  defineString("WS63_CONSOLE_COLOR_OK", config.palette.ok),
  defineString("WS63_CONSOLE_COLOR_BAD", config.palette.bad),
  defineString("WS63_CONSOLE_COLOR_WARN", config.palette.warn),
  "",
  "#endif",
  "",
];

fs.writeFileSync(outputPath, `${lines.join("\n")}\n`);
